# Generated by Django 4.2.16 on 2024-10-27 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docresinterno',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='docreslaboratorio',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='exinterno',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='exinterno',
            name='doctor',
            field=models.ForeignKey(blank=True, db_column='doctor_encargado', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
        migrations.AddField(
            model_name='exlaboratorio',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
    ]
