# Generated by Django 4.2.15 on 2024-09-14 04:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicamentos', '__first__'),
        ('paciente', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_column='fecha', default=datetime.datetime(2024, 9, 13, 22, 57, 16, 198840), verbose_name='Fecha de Cita')),
                ('numaut', models.CharField(db_column='numaut', max_length=80, verbose_name='Número de autorización')),
                ('numserie', models.CharField(db_column='numserie', max_length=80, verbose_name='Número de Serie')),
                ('dte', models.CharField(db_column='dte', max_length=80, verbose_name='DTE')),
                ('facturado', models.BooleanField(db_column='facturado', default=False, verbose_name='Facturado')),
                ('totalpago', models.DecimalField(db_column='totalpago', decimal_places=2, default=0, max_digits=10, verbose_name='Total Pago')),
                ('totalpagado', models.DecimalField(db_column='totalpagado', decimal_places=2, default=0, max_digits=10, verbose_name='Total Pagado')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'Cita',
            },
        ),
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEstado', models.CharField(blank=True, db_column='NombreEstado', max_length=30, null=True, verbose_name='Estado de cita')),
            ],
            options={
                'verbose_name': 'Estado de Cita',
                'verbose_name_plural': 'Estado de Citas',
                'db_table': 'EstadoCita',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, db_column='motivo', max_length=80, null=True, verbose_name='Motivo de cita')),
                ('historiaenfer', models.CharField(blank=True, db_column='historiaenfer', max_length=80, null=True, verbose_name='Historia de enfermedad')),
                ('presionarterial', models.CharField(blank=True, db_column='presionarterial', max_length=20, null=True, verbose_name='Presión Arterial')),
                ('frecuenciacard', models.CharField(blank=True, db_column='frecuenciiacard', max_length=5, null=True, verbose_name='Frecuencia Cardíaca')),
                ('frecuenciaresp', models.CharField(blank=True, db_column='frecuenciaresp', max_length=5, null=True, verbose_name='Frecuencia Respiratoria')),
                ('temperatura', models.CharField(blank=True, db_column='temperatura', max_length=5, null=True, verbose_name='Temperatura')),
                ('saturacion', models.CharField(blank=True, db_column='saturacion', max_length=5, null=True, verbose_name='Saturación')),
                ('glucosa', models.CharField(blank=True, db_column='glucosa', max_length=5, null=True, verbose_name='Glucosa')),
                ('peso', models.CharField(blank=True, db_column='peso', max_length=5, null=True, verbose_name='Peso')),
                ('altura', models.CharField(blank=True, db_column='altura', max_length=5, null=True, verbose_name='Altura')),
                ('diagnostico', models.CharField(blank=True, db_column='diagnostico', max_length=80, null=True, verbose_name='Diagnóstico')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
                'db_table': 'Historial',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreservicio', models.CharField(db_column='nombreservicio', max_length=30, verbose_name='Nombre del Servicio')),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=80, null=True, verbose_name='Descripción del Servicio')),
                ('costo', models.DecimalField(db_column='costo', decimal_places=2, max_digits=10, verbose_name='Costo del Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicio',
            },
        ),
        migrations.CreateModel(
            name='DetalleCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cita', models.ForeignKey(db_column='cita_id', on_delete=django.db.models.deletion.CASCADE, to='clinica.cita', verbose_name='Cita')),
                ('historial', models.ForeignKey(db_column='historial_id', on_delete=django.db.models.deletion.CASCADE, to='clinica.historial', verbose_name='Historial')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, to='clinica.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Cita',
                'verbose_name_plural': 'Detalle de Citas',
                'db_table': 'DetalleCita',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='estadocita',
            field=models.ForeignKey(db_column='estadocita_id', on_delete=django.db.models.deletion.CASCADE, to='clinica.estadocita', verbose_name='Estado de Cita'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='cita',
            name='recetamedica',
            field=models.ForeignKey(db_column='recetamedica_id', on_delete=django.db.models.deletion.CASCADE, to='medicamentos.recetamedica', verbose_name='Receta Médica'),
        ),
    ]
