# Generated by Django 4.2.15 on 2024-10-02 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicamentos', '0001_initial'),
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='cita',
            name='recetamedica',
            field=models.ForeignKey(db_column='recetamedica_id', on_delete=django.db.models.deletion.CASCADE, to='medicamentos.recetamedica', verbose_name='Receta médica'),
        ),
    ]
