# Generated by Django 4.2.15 on 2024-09-14 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_cita_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2024, 9, 13, 22, 57, 51, 390985), verbose_name='Fecha de Cita'),
        ),
    ]
