# Generated by Django 4.2.16 on 2024-10-27 04:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0003_detallerecetame_activo_medicamento_activo_and_more'),
        ('clinica', '0003_alter_cita_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('EE', 'En espera'), ('EC', 'En consulta'), ('F', 'Finalizada'), ('C', 'Cancelada')], db_column='estado', default='EE', max_length=2, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='detallecita',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='detallecita',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='historial',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='dte',
            field=models.CharField(blank=True, db_column='dte', max_length=80, null=True, verbose_name='DTE'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2024, 10, 26, 22, 53, 43, 406573), verbose_name='Fecha de cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='numaut',
            field=models.CharField(blank=True, db_column='numaut', max_length=80, null=True, verbose_name='Número de autorización'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='numserie',
            field=models.CharField(blank=True, db_column='numserie', max_length=80, null=True, verbose_name='Número de serie'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='recetamedica',
            field=models.ForeignKey(blank=True, db_column='recetamedica_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.recetamedica', verbose_name='Receta médica'),
        ),
        migrations.AlterField(
            model_name='detallecita',
            name='historial',
            field=models.ForeignKey(blank=True, db_column='historial_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.historial', verbose_name='Historial'),
        ),
        migrations.AlterField(
            model_name='detallecita',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
    ]
