# Generated by Django 4.2.16 on 2024-10-27 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0004_alter_recetamedica_fecha'),
        ('clinica', '0004_cita_activo_cita_estado_detallecita_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='dte',
            field=models.CharField(blank=True, db_column='dte', default=None, max_length=80, null=True, verbose_name='DTE'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estadocita',
            field=models.ForeignKey(blank=True, db_column='estadocita_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.estadocita', verbose_name='Estado de cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2024, 10, 27, 2, 49, 51, 769944), verbose_name='Fecha de cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='numaut',
            field=models.CharField(blank=True, db_column='numaut', default=None, max_length=80, null=True, verbose_name='Número de autorización'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='numserie',
            field=models.CharField(blank=True, db_column='numserie', default=None, max_length=80, null=True, verbose_name='Número de serie'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='recetamedica',
            field=models.ForeignKey(blank=True, db_column='recetamedica_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.recetamedica', verbose_name='Receta médica'),
        ),
    ]
