# Generated by Django 4.2.16 on 2024-10-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedente',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='contactopaciente',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='tipoantecedente',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(db_column='apellido', max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechanac',
            field=models.DateField(db_column='fechanac', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=30, verbose_name='Nombre'),
        ),
    ]
