# Generated by Django 4.2.15 on 2024-09-14 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactopaciente',
            options={'verbose_name': 'Contacto de paciente', 'verbose_name_plural': 'Contactos de pacientes'},
        ),
        migrations.AlterModelOptions(
            name='tipoantecedente',
            options={'verbose_name': 'Tipo de antecedente', 'verbose_name_plural': 'Tipo de antecedentes'},
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='tipoantecedente',
            field=models.ForeignKey(db_column='tipoantecedente', on_delete=django.db.models.deletion.CASCADE, to='paciente.tipoantecedente', verbose_name='Tipo de antecedente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechanac',
            field=models.DateField(blank=True, db_column='fechanac', null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
