# Generated by Django 4.2.16 on 2024-10-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_antecedente_activo_contactopaciente_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(blank=True, db_column='apellido', default='', max_length=30, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechanac',
            field=models.DateField(blank=True, db_column='fechanac', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, db_column='nombre', default='', max_length=30, verbose_name='Nombre'),
        ),
    ]
