# Generated by Django 4.2.15 on 2024-09-14 04:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(db_column='medicamento', max_length=30, verbose_name='Medicamento')),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', max_length=255, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'db_table': 'medicamentos',
            },
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_column='fecha', default=datetime.datetime(2024, 9, 13, 22, 57, 32, 977901), verbose_name='Fecha de Receta')),
                ('observaciones', models.TextField(db_column='observaciones', max_length=255, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Receta Médica',
                'verbose_name_plural': 'Recetas Médicas',
                'db_table': 'recetamedica',
            },
        ),
        migrations.CreateModel(
            name='DetalleRecetaMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosiscantidad', models.TextField(db_column='dosiscantidad', max_length=255, verbose_name='Dosis en Cantidad')),
                ('dosistiempo', models.TextField(db_column='dosistiempo', max_length=255, verbose_name='Dosis en tiempo')),
                ('medicamento', models.ForeignKey(db_column='medicamento', on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento', verbose_name='Medicamento')),
                ('recetamedica', models.ForeignKey(db_column='recetamedica', on_delete=django.db.models.deletion.CASCADE, to='medicamentos.recetamedica', verbose_name='Receta Médica')),
            ],
            options={
                'verbose_name': 'Detalle de Receta Médica',
                'verbose_name_plural': 'Detalles de Recetas Médicas',
                'db_table': 'detallerecetamedica',
            },
        ),
    ]
