# Generated by Django 4.2.15 on 2024-10-12 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetamedica',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2024, 10, 12, 10, 44, 50, 423407), verbose_name='Fecha de receta'),
        ),
    ]
