# Generated by Django 4.2.15 on 2024-09-14 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallerecetame',
            options={'verbose_name': 'Detalle de receta médica', 'verbose_name_plural': 'Detalles de recetas médicas'},
        ),
        migrations.AlterModelOptions(
            name='recetamedica',
            options={'verbose_name': 'Receta médica', 'verbose_name_plural': 'Recetas médicas'},
        ),
        migrations.AlterField(
            model_name='detallerecetame',
            name='dosiscantidad',
            field=models.TextField(db_column='dosiscantidad', max_length=255, verbose_name='Dosis en cantidad'),
        ),
        migrations.AlterField(
            model_name='detallerecetame',
            name='recetamedica',
            field=models.ForeignKey(db_column='recetamedica', on_delete=django.db.models.deletion.CASCADE, to='medicamentos.recetamedica', verbose_name='Receta médica'),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2024, 9, 14, 7, 37, 30, 95311), verbose_name='Fecha de receta'),
        ),
    ]
