# Generated by Django 4.2.16 on 2024-10-27 04:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicamentos', '0002_alter_recetamedica_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerecetame',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='doctor',
            field=models.ForeignKey(blank=True, db_column='doctor', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2024, 10, 26, 22, 53, 43, 403003), verbose_name='Fecha de receta'),
        ),
        migrations.AlterField(
            model_name='recetamedica',
            name='observaciones',
            field=models.TextField(blank=True, db_column='observaciones', max_length=255, null=True, verbose_name='Observaciones'),
        ),
    ]
