# Generated by Django 4.2.16 on 2024-10-27 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0003_detallerecetame_activo_medicamento_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetamedica',
            name='fecha',
            field=models.DateTimeField(db_column='fecha', default=datetime.datetime(2024, 10, 27, 2, 49, 51, 767433), verbose_name='Fecha de receta'),
        ),
    ]
