# Generated by Django 4.2.15 on 2024-10-02 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='nombre', max_length=30, verbose_name='Nombre tipo de pago')),
            ],
            options={
                'verbose_name': 'Tipo de pago',
                'verbose_name_plural': 'Tipos de pagos',
                'db_table': 'TipoPago',
            },
        ),
        migrations.CreateModel(
            name='ControlPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadpago', models.DecimalField(db_column='cantidadpago', decimal_places=2, max_digits=10, verbose_name='Cantidad de pago')),
                ('descripcion', models.TextField(blank=True, db_column='descripcion', max_length=255, null=True, verbose_name='Descripción')),
                ('numref', models.CharField(blank=True, db_column='numref', max_length=30, null=True, verbose_name='Número de referencia')),
                ('cita', models.ForeignKey(db_column='cita', on_delete=django.db.models.deletion.CASCADE, to='clinica.cita', verbose_name='Cita')),
                ('tipopago', models.ForeignKey(db_column='tipopago', on_delete=django.db.models.deletion.CASCADE, to='pagos.tipopago', verbose_name='Tipo de pago')),
            ],
            options={
                'verbose_name': 'Control de pago',
                'verbose_name_plural': 'Control de pagos',
                'db_table': 'ControlPago',
            },
        ),
    ]
