# Generated by Django 4.2.16 on 2024-10-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpago',
            name='activo',
            field=models.BooleanField(db_column='activo', default=False, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='activo',
            field=models.BooleanField(db_column='activo', default=False, verbose_name='Activo'),
        ),
    ]
