# Generated by Django 4.2.15 on 2024-09-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlpago',
            options={'verbose_name': 'Control de pago', 'verbose_name_plural': 'Control de pagos'},
        ),
        migrations.AlterModelOptions(
            name='tipopago',
            options={'verbose_name': 'Tipo de pago', 'verbose_name_plural': 'Tipos de pagos'},
        ),
    ]
