# Generated by Django 4.2.16 on 2024-10-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_controlpago_activo_tipopago_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpago',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipopago',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
    ]
