# Generated by Django 4.2.15 on 2024-09-14 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoperfil',
            options={'verbose_name': 'Tipo de perfil', 'verbose_name_plural': 'Tipo de perfiles'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fechanac',
            field=models.DateField(blank=True, db_column='fechanac', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.ForeignKey(blank=True, db_column='tipo_perfil_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipoperfil', verbose_name='Tipo de perfil'),
        ),
    ]
