# Generated by Django 4.2.16 on 2024-10-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_activo_tipoperfil_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True, verbose_name='Activo'),
        ),
    ]
